baseURL = "https://wcbt.github.io/Antons-site/"
languageCode = "en-us"
title = "My Hugo Resume Site"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    # Because your file is now directly in content/, 
    # the page URL is usually "/caibaitong_wang/"
    url = "/caibaitong_wang/"
    weight = 2
